### ISSUE TITLE
 Some APUs (Mullins and potentially others) have bad connectors

### ISSUE THREAD

**Issue by Zormeister** [NootInc/LegacyRed#5]
FB-only is currently broken on some APUs, notably my Mullins E1-7010 APU, currently the state of other APUs are unknown, however, current debugging shows that on my device at the least, `AtiAtomObjectinfoTable_V1::getAtomConnectorInfo` is failing at connector '3' which does not exist, this, presumably, brings down the whole stack and prevents display from going to the LVDS connector.

Update 1/8/23:
Attempts at overriding the value from within `AtiAtomObjectInfoTable_V1::getNumberOfConnectors` has proven futile at the current point in time

Update 7/8/23:
Attempts to grab the Display Object Path Table have been proven to be a success, now I need to figure out how to grab the object type and compare it against `GRAPH_OBJECT_TYPE_CONNECTOR`

**Comment by samgreat1402** [comment]
I got this kernel panic in amd-fx8800p carizzo when trying to boot bigsur installation using opencore
![043ad43c-54cf-4491-9b71-7d7bf3b96563](https://github.com/NootInc/LegacyRed/assets/135067347/314e54e2-5c73-4edc-9d5a-63ee67b6a651)
[vbios.txt](https://github.com/NootInc/LegacyRed/files/11991090/vbios.txt)
[config.zip](https://github.com/NootInc/LegacyRed/files/11991093/config.zip)

**Comment by ChefKissInc** [comment]
I am pretty sure a custom build of Lilu is required

**Comment by samgreat1402** [comment]
![Screenshot_2023-07-12-16-40-30-637_com miui videoplayer-edit](https://github.com/NootInc/LegacyRed/assets/135067347/32ae6282-eb69-41ab-8900-fd221df75653)
The error with last update

**Comment by ChefKissInc** [comment]
@samgreat1402 custom, as in custom
https://github.com/Zorm-Industries/Lilu
